# Debug mode
app.debug.level=2
app.debug.entity.filter=
app.debug.logger.filter=DEBUG,INFO,WARN,ERROR
# Window definition
app.window.width=640
app.window.height=480
app.window.full.screen=false
# Rendering configuration
app.render.fps=60
app.render.buffer.width=320
app.render.buffer.height=240
# physic engine
app.update.ups=60
app.world.gravity=0.0981
app.world.play.area.width=800
app.world.play.area.height=600
